### PR TITLE
API implementation

### PR DESCRIPTION
**Pull request by bipin-epam**
1. Added APIs
2. Unit Tests for APIs

### CODE REVIEW

**Comment by bipin-epam** [comment]
**What was done**

- API created along with Unit Tests and Swagger Documentation.
- Integration with frontend for required API is done.
- [FE Link](https://d2y0gfr893n94s.cloudfront.net/)
- [Base API Link](https://ycwify3l95.execute-api.ap-south-1.amazonaws.com/)
- [FE PR Link](https://github.com/bipin-epam/shop-react-redux-cloudfront/pull/2)
- [Swagger Link](https://ycwify3l95.execute-api.ap-south-1.amazonaws.com/dev/swagger)

**Comment by olena-kuchynska** [comment]
Hi, 
After review, I see that you don't use Webpack/ESbuild. Do you decide to skip this additional task?

When I checked integration with the front-end I saw that the request for getting product by ID is sent but the response doesn't display in UI.
image

**Comment by bipin-epam** [comment]
Hi @Olena-Bulatova , I've added the webpack configuration in the project. Please review and let me know if there is anything else. I've decided not to integrate optional `products/{id}` api for now.

**Comment by olena-kuchynska** [comment]
Great job! I didn't see that I should approve PR before merging it, so just put a grade on learning portal.

**Pull request merged**
